is_debug: true
server:
  port: 5555


swagger:
  title: "crypto-doc-sign-BE API"
  version: "1.0"
  base-path: "/v1"
  host: "127.0.0.1:5555"
  schemes:
    - "http"
    - "https"

storage:
  host: db
  port: 5432
  database: postgres
  username: postgres
  password: postgres
  connection_attempts: 3

logger:
  formatter: json
  out: stdout

generator:
  master_key: d0v90jsfd0jvs9jfv0f
  bit_size: 4096